engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
    checks:
      GoLint/Comments/PackageComments:
        enabled: false
  govet:
    enabled: true

exclude_patterns:
- ".github/"
- "vendor/"
- "codegen/"
