default:
  deps: [test]

update-deps:
  desc: Updates dependencies
  cmds:
    - dep ensure
    - dep ensure -update

lint:
  desc: Runs golint
  cmds:
    - go fmt -l $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
  silent: true

test:
  desc: Runs go tests
  cmds:
    - go test -race  .

test-coverage:
  desc: Runs go tests and calucates test coverage
  cmds:
    - go test -coverprofile=c.out .
