version: '3'

tasks:
  default:
    deps: [test]

  lint:
    desc: Checks code style
    cmds:
      - gofmt -d -s .
      - find -name go.mod -execdir go vet ./... \;
    silent: true

  lint-fix:
    desc: Fixes code style
    cmds:
      - gofmt -w -s .

  test:
    desc: Runs go tests
    cmds:
      - find -name go.mod -execdir go test -race ./... \;

  test-coverage:
    desc: Runs go tests and calculates test coverage
    cmds:
      - find -name go.mod -execdir go test -race -coverprofile=c.out ./... \;
