dl-deps:
  desc: Downloads cli dependencies
  cmds:
    - go get -u github.com/golang/lint/golint
    - go get -u github.com/golang/dep/cmd/dep

update-deps:
  desc: Updates dependencies
  cmds:
    - dep ensure
    - dep ensure -update
    - dep prune

test:
  desc: Run all the go tests.
  cmds:
    - go test -race  .
